services:
  neo4j:
    image: docker.io/library/neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt

  qdrant:
    image: docker.io/qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
